# fly.toml app configuration file generated for esquila-cloud on 2026-08-04T20:37:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esquila-cloud'
primary_region = 'iad'

[build]
  dockerfile = 'cloud/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
